In [1]:
# Why use NumPy -
#
# Python lists are flexible but slow for numerical computing because they:
#
# Store elements as pointers instead of a continuous block of memory.
# Lack vectorized operations, relying on loops instead.
# Have significant overhead due to dynamic typing.

In [2]:
# NumPy's Superpowers:
#
# Faster than Python lists (C-optimized backend)
# Uses less memory (efficient storage)
# Supports vectorized operations (no explicit loops needed)
# Has built-in mathematical functions

In [3]:
# NumPy vs. Python Lists – Performance Test -
# Let's compare Python lists with NumPy arrays using a simple example.

# Example 1: Adding Two Lists vs. NumPy Arrays -

import time

size = 1000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [a+b for a,b in zip(list1,list2)]
end = time.time()
print("Python list result time",end - start)


Python list result time 0.0002040863037109375


In [5]:
# Now using Numpy

import numpy as np

size = 1000
array1 = np.array(range(size))
array2 = np.array(range(size))
start1 = time.time()
result1 = array1 + array2
end1 = time.time()
print("Numpy array result time",end1 - start1)

# Key Takeaway: NumPy is significantly faster because it performs operations in C, avoiding Python loops.

Numpy array result time 5.5789947509765625e-05


In [6]:
# Creating NumPy Arrays
#
arr1 = np.array([1,2,3,4,5])
print(arr1)
#
#
# # Creating 2D Numpy arrays
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

# 🔹NumPy stores data in a contiguous memory block, making access faster than lists.
# Shape shows the dimensions of an array.


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [7]:
# Memory Efficiency – NumPy vs. Lists :
# Let's check memory consumption.

import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

size = sys.getsizeof(list_data) + sum(sys.getsizeof(x) for x in list_data)

print(" Python List bytes", size)  # 36056
print("NumPy array size:", numpy_data.nbytes, "bytes")  # 8000

# NumPy arrays use significantly less memory compared to Python lists.

 Python List bytes 36056
NumPy array size: 8000 bytes


In [9]:
# Vectorization – No More Loops!
#
# NumPy avoids loops by applying operations to entire arrays at once using SIMD (Single Instruction, Multiple Data)
# and other low-level optimizations. SIMD is a CPU-level optimization provided by modern processors.


# # # Example 2: Squaring Elements -

P_list_squares = [x ** 2 for x in list1]  #Python list (loop-based)

numpy_squares = arr1 ** 2  # NumPy (vectorized)

# # NumPy is cleaner and faster!

In [10]:
# Summary -
#
# NumPy is faster than Python lists because it is optimized in C.
# It consumes less memory due to efficient storage.
# It provides vectorized operations, removing the need for slow loops.
# Essential for data science and machine learning workflows.

In [11]:
# Exercises for Practice -

# 1. Create a NumPy array with values from 10 to 100 and print its shape.
import numpy as np
import time
NumArr = np.array(range(10, 101))
print(NumArr.shape)
# output = (91,) since it has 91 numbers total: 10, 11, 12, …, 99, 100.

(91,)


In [12]:
# 2. Compare the time taken to multiply two Python lists vs. two NumPy arrays.
l1 = [1,2,4]
l2 = [5,7,9]
LStart = time.time()
m_List = [a * b for a,b in zip(l1,l2)]
print(m_List)
LEnd = time.time()
print("Time for python list multiplication :",LEnd-LStart) #1.9073486328125e-06

Ar1 = np.array([1,2,4])
Ar2 = np.array([5,7,9])
nStart = time.time()
m_Numpy = Ar1 * Ar2
nEnd = time.time()
print("Time for numpy multiplication :",nEnd - nStart)

[5, 14, 36]
Time for python list multiplication : 0.0006661415100097656
Time for numpy multiplication : 0.0001418590545654297


In [13]:
# 3. Find the memory size of a NumPy array with 1 million elements.

arr = np.array(range(100000))
print("memory of arr is ",arr.nbytes)  #800000 bytes

memory of arr is  800000
