In [9]:
import numpy as np

In [10]:
!pip install numpy  # This is how we can use pip here.

In [11]:
arr = np.array([1, 3, 4])   # created a np array from a list 

In [12]:
arr  

array([1, 3, 4])

In [13]:
np.zeros((3, 4))    #to make an array of zero, takes a tupple 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((3, 5))     #to make an array of one, takes a tupple 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.full((4, 6), 8)    # to create an array of choice of shape and digit.

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [16]:
np.eye(3)    #identity - starts from 1 - 100,010,001 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(1, 100, 10)    # add.......# start stop n-1, add 10 

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [18]:
np.linspace(1, 100, 5)   # evenly spaced array, this one is devided by 5 spaces - start, stop, space 

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [19]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [20]:
myarr.shape  # to check shape in row column 

(4, 3)

In [21]:
myarr.size  # total nums of elements 

12

In [22]:
myarr.ndim  # to check dimension 2D = list of list, 3D = list of list of list [[[1,2]]]

2

In [23]:
myarr.dtype   # to check data type 

dtype('int64')

In [24]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]], dtype='float32')

In [25]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [26]:
n = myarr.astype('float64') #To create a copy of an array with a specified data type (dtype).

In [27]:
n.dtype

dtype('float64')

In [28]:
myarr.dtype

dtype('float32')

In [29]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [30]:
myarr.shape

(4, 3)

In [31]:
reshaped = myarr.reshape((3, 4)) # we can change the shape, (row , column) however there should be enough elements to reshape.

In [32]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [33]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [34]:
myarr.reshape((2, 6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 11, 12, 13]])

In [35]:
myarr.flatten()  # it converts array to a single dimension array 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])