In [33]:
# Indexing and slicing
# Lets now learn about indexing and slicing in Numpy

# Indexing (Same as Python Lists)

In [ ]:
# Slicing returns a view, not a copy! Changes affect the original array.**
# This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

# Why does this happen?

# Memory Efficiency: Avoids unnecessary copies, making operations faster and saving memory.
# Performance: Enables faster access and manipulation of large datasets without duplicating data.

In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [3]:
flat = arr.flatten()  # to created a 1 D array 

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [5]:
flat[0]  # indexing starts from 0 just like python

np.int64(1)

In [6]:
flat[3: 6]

array([4, 5, 6])

In [7]:
flat[:5] # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [8]:
flat[3:] # same as flat[3:13] len of array 

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [9]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [19]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [19]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [19]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [11]:
b = flat[3:7].copy() # This is not a slice because we are using copy method to get the copy

In [12]:
b

array([4, 5, 6, 7])

In [13]:
b[0] = 444444666   #changed the value of index 0 

In [14]:
b

array([444444666,         5,         6,         7])

In [15]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [16]:
arr = np.array([1, 54, 23, 53, 2, 3, 34, 5, 6])

In [20]:
arr[[1, 4, 6]]  # Fancy indexing (to get multiple elements of index) 1 = 54, 4 = 2, 6 = 34.

array([54,  2, 34])

In [18]:
arr[arr>23]    #Boolen masking filter data by giving the condition 

array([54, 53, 34])

In [ ]:
# If you slice without copy function, the actions will change the original array. Always make a copy to create a copy of array. 

In [32]:
# Mulitiple blocks array 
arr3 = np.array([
  [[1, 2, 3],
   [4, 5, 6]],   # 👈 Block 

  [[7, 8, 9],
   [10, 11, 12]]  # 👈 Block 
])

arr3.shape  # there are two blocks 

(2, 2, 3)

In [29]:
# ******** Exercises for Practice ********* - 

#1. Create a 3×3 array filled with random numbers and print its shape.

three = np.array([[[2,7,9],[5,8,6],[1,2,1]]])   # single block array 
three.shape

(1, 3, 3)

In [36]:
#2. Convert an array of floats [1.1, 2.2, 3.3] into integers.

arr_flt = np.array([1.1, 2.2, 3.3])   #created an array of floats 
print(arr_flt)

arr_Int = arr_flt.astype(np.int32) #converts float  to int 
print(arr_Int)

[1.1 2.2 3.3]
[1 2 3]


In [42]:
#3. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

arr = np.array([1, 2, 3, 4, 5, 6])
even = arr % 2 == 0 
print(arr[even])

[2 4 6]


In [43]:
#4. Reshape a 1D array of size 9 into a 3×3 matrix.

arr = np.array([1,4,6,7,8,9,3,4,6])
print(arr.reshape((3,3)))
arr.size

[[1 4 6]
 [7 8 9]
 [3 4 6]]


9

In [45]:
#5. Use boolean masking to filter numbers greater than 50 in an array.
arr = np.array([1,23,4,60,67,43,45,65,58,90,36])
greaterThanFifty = arr > 50
print(arr[greaterThanFifty])

[60 67 65 58 90]
